metadata.format.version = "1.1"

[versions]
velocity-api = "3.1.1"
blossom = "1.3.0"

[libraries]
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity-api" }

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
